In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [192]:
dataset = pd.read_csv('horse.csv')
x = dataset.iloc[:,np.r_[1:27]].values
y = dataset.iloc[:,0].values

In [193]:
print(x)

[['adult' 530101 38.5 ... 11300 0 0]
 ['adult' 534817 39.2 ... 2208 0 0]
 ['adult' 530334 38.3 ... 0 0 0]
 ...
 ['adult' 529386 37.5 ... 3205 0 0]
 ['adult' 530612 36.5 ... 2208 0 0]
 ['adult' 534618 37.2 ... 6112 0 0]]


In [ ]:
print(y)

['no' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'no' 'yes' 'no' 'yes'
 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'no'
 'yes' 'yes' 'yes' 'no' 'no' 'no' 'yes' 'yes' 'yes' 'no' 'no' 'yes' 'no'
 'yes' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'no' 'yes'
 'no' 'no' 'no' 'yes' 'yes' 'yes' 'yes' 'no' 'no' 'no' 'yes' 'no' 'yes'
 'yes' 'no' 'no' 'no' 'no' 'no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes'
 'yes' 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no'
 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'no' 'no' 'yes' 'yes' 'yes' 'yes' 'no' 'no' 'yes' 'no' 'yes'
 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'no' 'no'
 'no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'no' 'yes'
 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(x[:, 1:27])
x[:, 1:27] = imputer.transform(x[:, 1:27])

In [ ]:
print(x)

[['adult' 530101 38.5 ... 11300 0 0]
 ['adult' 534817 39.2 ... 2208 0 0]
 ['adult' 530334 38.3 ... 0 0 0]
 ...
 ['adult' 529386 37.5 ... 3205 0 0]
 ['adult' 530612 36.5 ... 2208 0 0]
 ['adult' 534618 37.2 ... 6112 0 0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,5,6,7,8,9,10,11,12,13,15,16,19,21,22])], remainder='passthrough')
x1 = np.array(ct.fit_transform(x))

In [ ]:
print(x1)

[[1.0 0.0 0.0 ... 11300 0 0]
 [1.0 0.0 0.0 ... 2208 0 0]
 [1.0 0.0 0.0 ... 0 0 0]
 ...
 [1.0 0.0 1.0 ... 3205 0 0]
 [1.0 0.0 0.0 ... 2208 0 0]
 [1.0 0.0 0.0 ... 6112 0 0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y1 = le.fit_transform(y)

In [ ]:
print(y1)

[0 1 0 1 0 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0
 1 0 1 1 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1
 1 1 1 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 1 0 0 1 0 1 1 1 0 1 0 1
 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1
 1 1 1 1 1 0 1 1 0 0 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0 1
 0 0 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 0 1 0 0 1 1 0 1 1 1 0 1 0
 1 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x1, y1, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[1.0 0.0 0.0 ... 0 0 0]
 [1.0 0.0 0.0 ... 3111 0 0]
 [1.0 0.0 0.0 ... 2111 0 0]
 ...
 [1.0 0.0 0.0 ... 2113 0 0]
 [1.0 0.0 0.0 ... 3111 0 0]
 [1.0 0.0 0.0 ... 3111 0 0]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 ... 3400 0 0]
 [1.0 0.0 0.0 ... 2124 0 0]
 [1.0 0.0 0.0 ... 7209 0 0]
 ...
 [1.0 0.0 0.0 ... 0 0 0]
 [1.0 0.0 0.0 ... 2207 0 0]
 [1.0 0.0 0.0 ... 5124 0 0]]


In [ ]:
print(y_train)

[0 0 1 1 1 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 0 1 1 0 1 1 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 1 0 1 1 1 0
 0 1 0 1 0 1 0 0 0 1 0 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 0 1 1
 0 0 0 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1 1 1 0 1 1 1 0 1 0
 1 0 0 0 1 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1
 1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 1 1 1 0 0
 0 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1]


In [ ]:
print(y_test)

[0 1 1 0 1 0 1 1 1 1 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 1 1
 0 0 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[1.0 0.0 0.0 ... -0.7310536753629666 -0.15626860163120768
  -0.06482037235521627]
 [1.0 0.0 0.0 ... -0.06917376728666311 -0.15626860163120768
  -0.06482037235521627]
 [1.0 0.0 0.0 ... -0.281928478979464 -0.15626860163120768
  -0.06482037235521627]
 ...
 [1.0 0.0 0.0 ... -0.2815029695560784 -0.15626860163120768
  -0.06482037235521627]
 [1.0 0.0 0.0 ... -0.06917376728666311 -0.15626860163120768
  -0.06482037235521627]
 [1.0 0.0 0.0 ... -0.06917376728666311 -0.15626860163120768
  -0.06482037235521627]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 ... -0.007687655607443657 -0.15626860163120768
  -0.06482037235521627]
 [1.0 0.0 0.0 ... -0.27916266772745757 -0.15626860163120768
  -0.06482037235521627]
 [1.0 0.0 0.0 ... 0.8026950412304349 -0.15626860163120768
  -0.06482037235521627]
 ...
 [1.0 0.0 0.0 ... -0.7310536753629666 -0.15626860163120768
  -0.06482037235521627]
 [1.0 0.0 0.0 ... -0.2615040266569551 -0.15626860163120768
  -0.06482037235521627]
 [1.0 0.0 0.0 ... 0.35910146735094506 -0.15626860163120768
  -0.06482037235521627]]
